from django.contrib import admin
from .models import LoginEvent

@admin.register(LoginEvent)
class LoginEventAdmin(admin.ModelAdmin):
    """
    Immutable Security and Login Activity Audit Trail.
    """
    list_display = (
        'timestamp',
        'event_type',
        'success',
        'get_user_display',
        'device',
        'ip_address',
    )
    list_filter = ('event_type', 'success', 'timestamp')
    search_fields = ('user__email', 'email_attempted', 'ip_address', 'device__device_name')
    ordering = ('-timestamp',)
    readonly_fields = (
        'id',
        'user',
        'email_attempted',
        'timestamp',
        'success',
        'event_type',
        'device',
        'ip_address',
        'user_agent',
    )

    def get_user_display(self, obj):
        return obj.user.email if obj.user else (obj.email_attempted or 'Unknown User')
    get_user_display.short_description = 'User / Attempted Email'

    def has_add_permission(self, request):
        # Audit log entries must only be generated by system events
        return False

    def has_change_permission(self, request, obj=None):
        # Audit log entries are immutable
        return False
