# Generated by Django 6.1.1 on 2026-09-04 05:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_attempted', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('success', models.BooleanField(default=True)),
                ('event_type', models.CharField(choices=[('LOGIN_SUCCESS', 'Successful Login'), ('LOGIN_FAILURE', 'Failed Login Attempt'), ('LOGOUT', 'User Logout'), ('NEW_DEVICE', 'New Device Detected'), ('DEVICE_TRUSTED', 'Device Trusted'), ('DEVICE_REVOKED', 'Device Revoked'), ('RECOVERY_USED', 'Recovery Key Verification Used'), ('PASSWORD_CHANGED', 'Account Password Changed')], db_index=True, max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_events', to='devices.device')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Login & Security Event',
                'verbose_name_plural': 'Login & Security Events',
                'db_table': 'vital_login_events',
                'ordering': ['-timestamp'],
            },
        ),
    ]
